export const alg = 'HS256';
export const secret = process.env.AUTH_SECRET;
export const key = new TextEncoder().encode(secret);
export const expiresIn = 60 * 60; // in s
export const TICKETS_LIMIT: number = 3;
export const MODE: 'dev' | 'prev' | 'prod' = 'dev';
export const MESSAGE_MAX_LENGTH = 250;
export const MIN_LENGTH_FIRSTNAME = 3;
export const MIN_LENGTH_LASTNAME = 3;
